name: Upgrade test (github/github-load-test)
on:
  workflow_dispatch:
  issue_comment:

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'uploaded!') && contains(github.event.issue.labels.*.name, 'testing')}}
    outputs:
      ghes-version: ${{ steps.extract.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract version and image url
        id: extract
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo $ISSUE_BODY | grep -oP '\b\d+\.\d+\.\d+(\.pre|\.gm|\.rc)\d+\b' | head -n 1 
          version=$(echo $ISSUE_BODY | grep -oP '\b\d+\.\d+\.\d+(\.pre|\.gm|\.rc)\d+\b' | head -n 1)
          echo $version

          if [[ "$string" =~ ^[a-zA-Z0-9.]+$ ]]; then
              echo "The string contains only alphabets, numbers, and dots."
          else
              echo "The string contains other characters."
              other_chars=$(echo "$version" | tr -d 'a-zA-Z0-9.' | tr -d '\n' | fold -w1 | sort -u | tr -d '\n')
              echo "Other characters: $other_chars"
          fi

          v='3.14.0.gm2'

          echo $v >> $GITHUB_OUTPUT

          echo "no error from v"

          echo "::extract name=iversion::3.14.0.gm2"

          echo "no error from iversion::3.14.0.gm2"
          
          echo "::extract name=version::$version"
  
  trigger_test:
    name: Echo output
    runs-on: ubuntu-latest
    steps:
    - name: echo output
      run: echo "${{ needs.issue_commented.outputs.ghes-version }}"
          
