name: Upgrade test (github/github-load-test)
on:
  workflow_dispatch:
  issue_comment:

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'uploaded!') && contains(github.event.issue.labels.*.name, 'testing')}}
    outputs:
      ghes-version: ${{ steps.extract.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract version and image url
        id: extract
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          version=$(echo $ISSUE_BODY | grep -oP '\b\d+\.\d+\.\d+(\.pre|\.gm|\.rc)\d+\b' | head -n 1)          
          echo $version
          if [[ "$version" =~ ^[a-zA-Z0-9.]+$ ]]; then
              echo "The string contains only alphabets, numbers, and dots."
          else
              echo "The string contains other characters."
          fi
          cleaned_version=$(echo "$version" | tr -cd 'a-z0-9.')
          echo $cleaned_version
          echo $cleaned_version >> $GITHUB_OUTPUT

          

     
          
          
          # echo $cleaned_version
          # echo "::extract name=version::$cleaned_version"

          # echo "no error from cleaned_version"

          # echo $cleaned_version >> $GITHUB_OUTPUT

          # echo "no error from GITHUB_OUTPUT"
  
  trigger_test:
    name: Echo output
    runs-on: ubuntu-latest
    steps:
    - name: echo output
      run: echo "${{ needs.issue_commented.outputs.ghes-version }}"
          
