name: Upgrade test (github/github-load-test)
on:
  workflow_dispatch:
  issue_comment:

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'uploaded!') && contains(github.event.issue.labels.*.name, 'testing')}}
    outputs:
      ghes-version: ${{ steps.extract.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract version and image url
        id: extract
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo $ISSUE_BODY | grep -oP '\b\d+\.\d+\.\d+(\.pre|\.gm|\.rc)\d+\b' | head -n 1 
          version=$(echo $ISSUE_BODY | grep -oP '\b\d+\.\d+\.\d+(\.pre|\.gm|\.rc)\d+\b' | head -n 1)
          echo $version

          v="3.14.0.gm2"
          if [[ "$version" != "$v" ]]; then
              echo "The strings are not equal."
          else
              echo "The strings are equal."
          fi

          echo $v >> $GITHUB_OUTPUT

          echo "no error from v"
          
          # Check for leading spaces or newlines
          if [[ "$version" != "${version#"${version%%[![:space:]]*}"}" ]]; then
              echo "The string has leading spaces or newlines."
          fi
          
          # Check for trailing spaces or newlines
          if [[ "$version" != "${version%"${version##*[![:space:]]}"}" ]]; then
              echo "The string has trailing spaces or newlines."
          fi
          echo "::extract name=version::$version"
  
  trigger_test:
    name: Echo output
    steps:
    - name: echo output
      run: echo "${{ needs.issue_commented.outputs.ghes-version }}"
          
